[webservers]
web-1 ansible_host=51.250.3.182 fqdn=web-1.ru-central1.internal
web-2 ansible_host=111.88.242.205 fqdn=web-2.ru-central1.internal

[databases]
main ansible_host=111.88.250.214 fqdn=main.ru-central1.internal
replica ansible_host=89.169.147.160 fqdn=replica.ru-central1.internal

[storage]
storage ansible_host=158.160.37.11 fqdn=storage.ru-central1.internal
